name: Java CI/CD with Gradle, Docker, and Cloud Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0


      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/CI-CD_WithDockerAndAwsProject:latest

      - name: Copy JAR to Cloud via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CLOUD_HOST }}             # Bulut sunucusunun IP veya adresi
          username: ${{ secrets.CLOUD_USERNAME }}     # Bulut sunucusuna bağlanılacak kullanıcı adı
          key: ${{ secrets.CLOUD_SSH_KEY }}           # SSH özel anahtarı (daha güvenli)
          # VEYA şifre kullanmak isterseniz:
          # password: ${{ secrets.CLOUD_PASSWORD }}
          port: 22                                  # SSH portu (genellikle 22)
          source: "build/libs/*.jar"                # Kopyalanacak JAR dosyasının yolu (Gradle build'e göre değişebilir)
          target: "/path/on/your/server/"           # Sunucuda JAR dosyasının kopyalanacağı hedef dizin
          strip_components: 2                       # 'build/libs/' kısmını atlayarak sadece dosya adını kopyalar
